# Define la versión del archivo Compose (opcional pero recomendable)
# version: "3.8"
# docker-compose up -d
# Sección para definir los servicios del proyecto
version: '3.8'

services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

#echo "*:*:*:adminMeli:passwordMeli" > ~/.pgpass
#chmod 600 ~/.pgpass
#
#docker exec -it db-primary psql -U admin -d apidb -c "SELECT * FROM pg_stat_replication;"